game=["name","family","food","fruit","color","animal","city","country","object"]
print(game)
print("please answer the qyestions:")
str(input("which word do you want to start?"))
a=str(input("enter name:"))
print(a)
b=str(input("enter family:"))
print(b)
c=str(input("enter food:"))
print(c)
d=str(input("enter food:"))
print(d)
e=str(input("enter fruit:"))
print(e)
f=str(input("enter color:"))
print(f)
g=str(input("enter animal:"))
print(g)
h=str(input("enter city:"))
print(h)
i=str(input("enter country:"))
print(i)
j=str(input("enter object:"))
print(j)

print("done")